Repository ReDeployed/core, pull requests merged in 2023-05, with the labels that each got.

#43 Docker restructure with Deno Fetch Adapter
  api-src/api-test.js
  astro-src/Dockerfile
  astro-src/src/components/Api.svelte
  deno-src/Dockerfile
  deno-src/src/handler.js
  deno-src/src/webserver.ts
  docker-compose.yml
Labels: enhancement, Database

#44 add HTTPS proxy
  docker-compose.yml
  proxy/.gitignore
  proxy/conf/astro.conf
  proxy/ssl/README.md
Labels: enhancement

#45 Create Input corresponding Checks
  astro-src/src/components/Api.svelte
  astro-src/src/components/Api2.svelte
  astro-src/src/components/gatewayValidator.js
  astro-src/src/components/input.svelte
  astro-src/src/components/ipAddressValidator.js
  astro-src/src/components/subnetMaskValidator.js
  astro-src/src/pages/404.astro
  astro-src/src/pages/deploy.astro
Labels: enhancement

#46 Working HTTPS database handeling
  deno-src/src/auth/ca-certificate.pem
  deno-src/src/auth/csr.pem
  deno-src/src/auth/key.pem
  deno-src/src/dbHandler.js
  deno-src/src/handler.js
  deno-src/src/webserver.ts
Labels: enhancement

#47 Impliment Site Routing and File - Name/Syntax Cleanup
  astro-src/src/components/Api.astro
  astro-src/src/components/ApiCoffee.svelte
  astro-src/src/components/ApiDatabase.svelte
  astro-src/src/components/Button.svelte
  astro-src/src/components/DeviceImage.png
  astro-src/src/components/InputValidation.svelte
  astro-src/src/components/InputValidator.js
  astro-src/src/components/MainPage.svelte
  astro-src/src/components/MainTerminal.svelte
  astro-src/src/components/TestApiCalls.http
  astro-src/src/components/gatewayValidator.js
  astro-src/src/components/ipAddressValidator.js
  astro-src/src/components/subnetMaskValidator.js
  astro-src/src/pages/404.astro
  astro-src/src/pages/config.astro
  astro-src/src/pages/deploy.astro
  astro-src/src/pages/edit/[id].astro
  astro-src/src/pages/index.astro
  astro-src/src/pages/status/[id].astro
  astro-src/src/pages/terminal.astro
Labels: enhancement

#48 Added client functions for Svelte/Astro
  astro-src/src/auth/ca-certificate.pem
  astro-src/src/auth/csr.pem
  astro-src/src/auth/key.pem
  astro-src/src/clientfunctions.js
Labels: Database

#53 Reimplement HTTPS and improvements
  astro-src/package.json
  deno-src/Dockerfile
  deno-src/src/auth/ca-certificate.pem
  deno-src/src/auth/csr.pem
  deno-src/src/auth/key.pem
  deno-src/src/dbHandler.js
  deno-src/src/webserver.ts
  docker-compose.yml
  proxy/conf/astro.conf
Labels: enhancement

#54 Android API Endpoitn Addtion
  astro-src/astro.config.mjs
  astro-src/src/components/ApiDatabase.svelte
  astro-src/src/pages/api/[id].ts
  astro-src/src/public/img/DeviceImage.png
Labels: enhancement, Android

#49 Added database id search
  deno-src/src/ChkpHandler.js
  deno-src/src/apiHandler.js
  deno-src/src/dbHandler.js
  deno-src/src/eventHandler.js
  deno-src/src/webserver.ts
Labels: enhancement, Database

#58 Installer script addition
  install.sh
Labels: enhancement
