Repository ReDeployed/core, pull requests merged in 2023-06, with the labels that each got.

#57 Added authentification functions
  deno-src/src/ca/ca-certificate.pem
  deno-src/src/ca/csr.pem
  deno-src/src/ca/key.pem
  deno-src/src/chkpHandler.js
  deno-src/src/dbHandler.js
  deno-src/src/encryption.ts
  deno-src/src/eventHandler.js
  deno-src/src/run.ts
  deno-src/src/webserver.ts
Labels: enhancement, Database

#63 Add Checkpoint Integrations
  astro-src/src/components/ApiCoffee.svelte
  astro-src/src/components/ApiDev.svelte
  astro-src/src/components/ApiDevStatus.svelte
  astro-src/src/components/ApiEditDevice.svelte
  astro-src/src/components/ApiListing.svelte
  astro-src/src/components/InputValidation.svelte
  astro-src/src/components/MainPage.svelte
  astro-src/src/components/MainTerminal.svelte
  astro-src/src/components/TestApiCalls.http
  astro-src/src/pages/deploy.astro
  astro-src/src/pages/edit/[id].astro
  astro-src/src/pages/listing.astro
  astro-src/src/pages/status/[id].astro
  deno-src/Dockerfile
  deno-src/src/ChkpHandler.js
  deno-src/src/apiHandler.js
  deno-src/src/checkpoint-testing/addRouteTest.ts
  deno-src/src/checkpoint-testing/delRouteTest.ts
  deno-src/src/checkpoint-testing/getAllInterfacesTest.ts
  deno-src/src/checkpoint-testing/getDiagnostics.ts
  deno-src/src/checkpoint-testing/getHostnameTest.ts
  deno-src/src/checkpoint-testing/getInterfaceETH0Test.ts
  deno-src/src/checkpoint-testing/getStaticRoutesTest.ts
  deno-src/src/checkpoint-testing/getVersionTest.ts
  deno-src/src/checkpoint-testing/setInterface.ts
  deno-src/src/checkpoint-testing/switchInterface.ts
  deno-src/src/checkpointTest.ts
  deno-src/src/checkpointTests.ts
  deno-src/src/chkpHandler.js
  deno-src/src/chkpSim.js
  deno-src/src/dbHandler.js
  deno-src/src/eventHandler.js
  deno-src/src/showDiagnosticsCPU.json
  deno-src/src/simJSON/showDiagnosticsCPU.json
  deno-src/src/simJSON/showDiagnosticsMEM.json
  deno-src/src/simJSON/showHostname.json
  deno-src/src/simJSON/showInterfaces.json
  deno-src/src/simJSON/showVersion.json
  deno-src/src/webserver.ts
Labels: enhancement, CheckPoint, Database

#67 Add TailwindCSS
  astro-src/astro.config.mjs
  astro-src/package-lock.json
  astro-src/package.json
  astro-src/src/auth/ca-certificate.pem
  astro-src/src/auth/csr.pem
  astro-src/src/auth/key.pem
  astro-src/src/components/MainPage.svelte
  astro-src/src/components/MainTerminal.svelte
  astro-src/src/pages/404.astro
  astro-src/src/pages/deploy.astro
  astro-src/src/pages/edit/[id].astro
  astro-src/src/pages/index.astro
  astro-src/src/pages/listing.astro
  astro-src/src/pages/settings.astro
  astro-src/src/pages/status/[id].astro
  astro-src/src/pages/terminal.astro
  astro-src/src/public/img/redeploy_logo_full.jpg
  astro-src/tailwind.config.cjs
Labels: enhancement

#70 Change/Frontend + Implement Add Function and everything needed for it
  astro-src/Dockerfile
  astro-src/src/components/ApiDev.svelte
  astro-src/src/components/ApiDevAdition.svelte
  astro-src/src/components/ApiDevStatus.svelte
  astro-src/src/components/ApiListing.svelte
  astro-src/src/components/InputValidator.js
  astro-src/src/components/MainPage.svelte
  astro-src/src/pages/create.astro
  deno-src/src/eventHandler.js
Labels: enhancement

#71 Android API Impmenetations for Listing and Auth
  astro-src/Dockerfile
  astro-src/package-lock.json
  astro-src/src/pages/api/[id].ts
  deno-src/Dockerfile
  deno-src/src/apiHandler.js
  deno-src/src/checkpointTest.ts
  deno-src/src/checkpointTests.ts
  deno-src/src/chkpHandler.js
  deno-src/src/dbHandler.js
  deno-src/src/encryption.ts
  deno-src/src/eventHandler.js
  deno-src/src/run.ts
  deno-src/src/showDiagnosticsCPU.json
  deno-src/src/webserver.ts
  docker-compose.yml
Labels: enhancement, Android

#72 Design Overhaul
  astro-src/src/components/ApiListing.svelte
  astro-src/src/components/MainPage.svelte
  astro-src/src/components/MainTerminal.svelte
Labels: enhancement

#73 CORS fixes and less empty code
  astro-src/src/components/ApiDev.svelte
  astro-src/src/components/ApiDevStatus.svelte
  astro-src/src/components/ApiListing.svelte
  deno-src/src/chkpSim.js
  deno-src/src/eventHandler.js
  deno-src/src/webserver.ts
Labels: enhancement

#75 Last Android API Additions
  astro-src/src/pages/api/[id].ts
Labels: enhancement, Android
